[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[project]
authors = [
    { name = "Michael Foord" },
    { name = "James Bennett" },
]
maintainers = [
    { name = "James Bennett" }
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Environment :: Web Environment",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: BSD License",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Topic :: Utilities",
]
name = "akismet"
description = "A Python interface to the Akismet spam-filtering service."
dependencies = [
    "httpx",
    "typing-extensions",
]
keywords = ["akismet", "spam", "spam-filtering"]
license = { text = "BSD-3-Clause" }
readme = "README.rst"
requires-python = ">=3.9"
version = "24.11.1a0"

[dependency-groups]
tests = [
    "anyio",
    "coverage[toml]",
    "pytest",
]

[project.urls]
"Documentation" = "https://akismet.readthedocs.io"
"Source Code" = "https://github.com/ubernostrum/akismet"

[tool.bandit]
skips = ["B101", "B113"]

[tool.black]
target-version = ["py39", "py310", "py311", "py312", "py313"]

[tool.coverage.paths]
source = ["src", ".nox/tests_with_coverage*/**/site-packages"]

[tool.coverage.report]
fail_under = 100

[tool.coverage.run]
branch = true
parallel = true
source = ["akismet"]

[tool.interrogate]
fail-under = 100
ignore-init-method = true
ignore-init-module = true

[tool.isort]
profile = "black"

[tool.pdm]
distribution = true

[tool.pdm.build]
source-includes = [
    ".editorconfig",
    ".flake8",
    ".pre-commit-config.yaml",
    ".readthedocs.yaml",
    "AUTHORS",
    "CONTRIBUTING.rst",
    "Makefile",
    "docs/",
    "noxfile.py",
    "pdm.lock",
    "runtests.py",
    "tests/",
]

[tool.pylint]
disable = [
    "duplicate-code",
    "protected-access",
]

[tool.pytest.ini_options]
filterwarnings = [
    "ignore::pytest.PytestCollectionWarning",
]
markers = [
    "akismet_async_client",
    "akismet_exception_response",
    "akismet_fixed_response",
    "akismet_sync_client",
    "api",
    "async_client",
    "constructors",
    "end_to_end",
    "errors",
    "sync_client",
    "test_client",
]
