---
name: CI

on:
  push:
    branches: [trunk]
    tags: ["*"]
  pull_request:
    branches: [trunk]
  workflow_dispatch:

env:
  FORCE_COLOR: "1"
  PIP_DISABLE_VERSION_CHECK: "1"
  TEST_AKISMET_API_KEY: ${{ secrets.TEST_AKISMET_API_KEY }}
  TEST_AKISMET_BLOG_URL: ${{ secrets.TEST_AKISMET_BLOG_URL }}

permissions:
  contents: read

jobs:
  tests:
    name: nox on ${{ matrix.python-version }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@1b05615854632b887b69ae1be8cbefe72d3ae423 # v2.6.0
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            docs.python.org:443
            files.pythonhosted.org:443
            github.com:443
            pypi.org:443
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: "Install dependencies"
        run: |
          python -VV
          python -Im site
          python -Im pip install --upgrade pip setuptools wheel
          python -Im pip install --upgrade nox
          python -Im nox --version
      - name: "Run CI suite with nox"
        run: "python -Im nox --non-interactive --python ${{ matrix.python-version }}"
